Skill.find_by(name: 'API development ')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'AWS')&.update_attributes( skill_type: 'service')
Skill.find_by(name: 'Active Admin')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'Ajax')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'Amazon S3')&.update_attributes( skill_type: 'service')
Skill.find_by(name: 'Amazon EC2')&.update_attributes( skill_type: 'service')
Skill.find_by(name: 'Android SDK')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'Angular')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'Angular Material')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'AngularJs')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'Ansible')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Apache')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Apache spark')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Arkit')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Autolayout')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'BDD')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Backbone.js')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'Background jobs')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Bigdata')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Bitbucket')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Bluebird')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Bower')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'C++')&.update_attributes( skill_type: 'programming_language')
Skill.find_by(name: 'CRM')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'CRUD')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Capistrano')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'Capybara')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'Carrierwave')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'Cloudera impala')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Cocoa')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'CocoaPods')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Codeship')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Coffeescript')&.update_attributes( skill_type: 'programming_language')
Skill.find_by(name: 'Composer')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Core Data')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Core location')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Crashlytics')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'Cucumber')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'DRY')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Dagger2')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'Dependency Injection')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Devise')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'Drupal')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'DynamoDB')&.update_attributes( skill_type: 'database')
Skill.find_by(name: 'E-commerce')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Ehcache')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'ElasticSearch')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'EmberJs')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'ExpressJS')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'FabrickJs')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'Facebook SDK')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'Flex')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'GRASP patterns')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Git')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Glide')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Google directions')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'Google maps')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'Google places')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Google SDK')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'Google services')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'Google+')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Grunt')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Gulp')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Gulp.js')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'HDFS')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'HTML')&.update_attributes( skill_type: 'programming_language')
Skill.find_by(name: 'Hadoop')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Hapi.js')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Heroku')&.update_attributes( skill_type: 'service')
Skill.find_by(name: 'Hibernate')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'I18n')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'J2EE')&.update_attributes( skill_type: 'programming_language')
Skill.find_by(name: 'J2SE')&.update_attributes( skill_type: 'programming_language')
Skill.find_by(name: 'JQuery')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'JSdom')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Jade')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Java')&.update_attributes( skill_type: 'programming_language')
Skill.find_by(name: 'Java servlets')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'Javascript')&.update_attributes( skill_type: 'programming_language')
Skill.find_by(name: 'Jenkins')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Jersey')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Joomla')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'JSON')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Junit')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'KnockoutJS')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Laravel')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'LESS')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Linux')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Lodash.js')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'MVC')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Machine learning')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'MariaDB')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Marketch')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Memcached')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Mercurial')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'MongoDB')&.update_attributes( skill_type: 'database')
Skill.find_by(name: 'Mongoose')&.update_attributes( skill_type: 'database')
Skill.find_by(name: 'Morphia')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Mustache.js')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'MySQL')&.update_attributes( skill_type: 'database')
Skill.find_by(name: 'NPM')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Native Web Sockets')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'NodeJS')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'NodeMailer')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'Notifications')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'OAuth')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'OOP')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Objective-c')&.update_attributes( skill_type: 'programming_language')
Skill.find_by(name: 'PHP')&.update_attributes( skill_type: 'programming_language')
Skill.find_by(name: 'Passport.js')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'Payoneer')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Paypal')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'PhantomJs')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'Picasso')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'Plivo')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'PostgreSQL')&.update_attributes( skill_type: 'database')
Skill.find_by(name: 'Pusher')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'Quill.js')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'ReactiveX')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Redmine')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Resque')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'Rest')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Rest API')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Retrofit2')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'Rubocop')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'Ruby')&.update_attributes( skill_type: 'programming_language')
Skill.find_by(name: 'Ruby on Rails')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'RxAndroid')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'RxJava')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'SCSS')&.update_attributes( skill_type: 'programming_language')
Skill.find_by(name: 'SNS')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'SOLID')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'SQL')&.update_attributes( skill_type: 'programming_language')
Skill.find_by(name: 'SQLite')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'SSH')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'SVN')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'SailsJs')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Sass')&.update_attributes( skill_type: 'programming_language')
Skill.find_by(name: 'Sidekiq')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'Sinatra')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'Sketch')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Slim')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Spark ml')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Spring')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'Stripe')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'TDD')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Teamcity')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Tomcat')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Trello')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Twilio')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Twitter SDK')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'Twitter-bootstrap')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'UI')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'UX design')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Umi-cms')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Underscore.js')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'Vagrant')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Vue.js')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'Webpacker')&.update_attributes( skill_type: 'library')
Skill.find_by(name: 'Websockets')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Woocommerce')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'XHTML')&.update_attributes( skill_type: 'programming_language')
Skill.find_by(name: 'Yii')&.update_attributes( skill_type: 'framework')
Skill.find_by(name: 'Zeplin')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'Zeromq')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'iOS')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'lynx')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'mLab')&.update_attributes( skill_type: 'other_skill')
Skill.find_by(name: 'xCode')&.update_attributes( skill_type: 'other_skill')
