Skill.create!(name: 'API development ', skill_type: 'other_skill')
Skill.create!(name: 'AWS', skill_type: 'service')
Skill.create!(name: 'Active Admin', skill_type: 'library')
Skill.create!(name: 'Ajax', skill_type: 'library')
Skill.create!(name: 'Amazon S3', skill_type: 'service')
Skill.create!(name: 'Amazon EC2', skill_type: 'service')
Skill.create!(name: 'Android SDK', skill_type: 'framework')
Skill.create!(name: 'Angular', skill_type: 'framework')
Skill.create!(name: 'Angular Material', skill_type: 'framework')
Skill.create!(name: 'AngularJs', skill_type: 'framework')
Skill.create!(name: 'Ansible', skill_type: 'other_skill')
Skill.create!(name: 'Apache', skill_type: 'other_skill')
Skill.create!(name: 'Apache spark', skill_type: 'other_skill')
Skill.create!(name: 'Arkit', skill_type: 'other_skill')
Skill.create!(name: 'Autolayout', skill_type: 'other_skill')
Skill.create!(name: 'BDD', skill_type: 'other_skill')
Skill.create!(name: 'Backbone.js', skill_type: 'framework')
Skill.create!(name: 'Background jobs', skill_type: 'other_skill')
Skill.create!(name: 'Bigdata', skill_type: 'other_skill')
Skill.create!(name: 'Bitbucket', skill_type: 'other_skill')
Skill.create!(name: 'Bluebird', skill_type: 'other_skill')
Skill.create!(name: 'Bower', skill_type: 'other_skill')
Skill.create!(name: 'C++', skill_type: 'programming_language')
Skill.create!(name: 'CRM', skill_type: 'other_skill')
Skill.create!(name: 'CRUD', skill_type: 'other_skill')
Skill.create!(name: 'Capistrano', skill_type: 'library')
Skill.create!(name: 'Capybara', skill_type: 'library')
Skill.create!(name: 'Carrierwave', skill_type: 'library')
Skill.create!(name: 'Cloudera impala', skill_type: 'other_skill')
Skill.create!(name: 'Cocoa', skill_type: 'other_skill')
Skill.create!(name: 'CocoaPods', skill_type: 'other_skill')
Skill.create!(name: 'Codeship', skill_type: 'other_skill')
Skill.create!(name: 'Coffeescript', skill_type: 'programming_language')
Skill.create!(name: 'Composer', skill_type: 'other_skill')
Skill.create!(name: 'Core Data', skill_type: 'other_skill')
Skill.create!(name: 'Core location', skill_type: 'other_skill')
Skill.create!(name: 'Crashlytics', skill_type: 'library')
Skill.create!(name: 'Cucumber', skill_type: 'other_skill')
Skill.create!(name: 'DRY', skill_type: 'other_skill')
Skill.create!(name: 'Dagger2', skill_type: 'library')
Skill.create!(name: 'Dependency Injection', skill_type: 'other_skill')
Skill.create!(name: 'Devise', skill_type: 'library')
Skill.create!(name: 'Drupal', skill_type: 'framework')
Skill.create!(name: 'DynamoDB', skill_type: 'database')
Skill.create!(name: 'E-commerce', skill_type: 'other_skill')
Skill.create!(name: 'Ehcache', skill_type: 'other_skill')
Skill.create!(name: 'ElasticSearch', skill_type: 'other_skill')
Skill.create!(name: 'EmberJs', skill_type: 'framework')
Skill.create!(name: 'ExpressJS', skill_type: 'framework')
Skill.create!(name: 'FabrickJs', skill_type: 'framework')
Skill.create!(name: 'Facebook SDK', skill_type: 'library')
Skill.create!(name: 'Flex', skill_type: 'other_skill')
Skill.create!(name: 'GRASP patterns', skill_type: 'other_skill')
Skill.create!(name: 'Git', skill_type: 'other_skill')
Skill.create!(name: 'Glide', skill_type: 'other_skill')
Skill.create!(name: 'Google directions', skill_type: 'framework')
Skill.create!(name: 'Google maps', skill_type: 'framework')
Skill.create!(name: 'Google places', skill_type: 'other_skill')
Skill.create!(name: 'Google SDK', skill_type: 'framework')
Skill.create!(name: 'Google services', skill_type: 'framework')
Skill.create!(name: 'Google+', skill_type: 'other_skill')
Skill.create!(name: 'Grunt', skill_type: 'other_skill')
Skill.create!(name: 'Gulp', skill_type: 'other_skill')
Skill.create!(name: 'Gulp.js', skill_type: 'other_skill')
Skill.create!(name: 'HDFS', skill_type: 'other_skill')
Skill.create!(name: 'HTML', skill_type: 'programming_language')
Skill.create!(name: 'Hadoop', skill_type: 'other_skill')
Skill.create!(name: 'Hapi.js', skill_type: 'other_skill')
Skill.create!(name: 'Heroku', skill_type: 'service')
Skill.create!(name: 'Hibernate', skill_type: 'framework')
Skill.create!(name: 'I18n', skill_type: 'library')
Skill.create!(name: 'J2EE', skill_type: 'programming_language')
Skill.create!(name: 'J2SE', skill_type: 'programming_language')
Skill.create!(name: 'JQuery', skill_type: 'library')
Skill.create!(name: 'JSdom', skill_type: 'other_skill')
Skill.create!(name: 'Jade', skill_type: 'other_skill')
Skill.create!(name: 'Java', skill_type: 'programming_language')
Skill.create!(name: 'Java servlets', skill_type: 'framework')
Skill.create!(name: 'Javascript', skill_type: 'programming_language')
Skill.create!(name: 'Jenkins', skill_type: 'other_skill')
Skill.create!(name: 'Jersey', skill_type: 'other_skill')
Skill.create!(name: 'Joomla', skill_type: 'framework')
Skill.create!(name: 'JSON', skill_type: 'other_skill')
Skill.create!(name: 'Junit', skill_type: 'framework')
Skill.create!(name: 'KnockoutJS', skill_type: 'other_skill')
Skill.create!(name: 'Laravel', skill_type: 'framework')
Skill.create!(name: 'LESS', skill_type: 'other_skill')
Skill.create!(name: 'Linux', skill_type: 'other_skill')
Skill.create!(name: 'Lodash.js', skill_type: 'library')
Skill.create!(name: 'MVC', skill_type: 'other_skill')
Skill.create!(name: 'Machine learning', skill_type: 'other_skill')
Skill.create!(name: 'Marketch', skill_type: 'other_skill')
Skill.create!(name: 'Memcached', skill_type: 'other_skill')
Skill.create!(name: 'Mercurial', skill_type: 'other_skill')
Skill.create!(name: 'MongoDB', skill_type: 'database')
Skill.create!(name: 'Mongoose', skill_type: 'database')
Skill.create!(name: 'Morphia', skill_type: 'other_skill')
Skill.create!(name: 'Mustache.js', skill_type: 'other_skill')
Skill.create!(name: 'MySQL', skill_type: 'database')
Skill.create!(name: 'NPM', skill_type: 'other_skill')
Skill.create!(name: 'Native Web Sockets', skill_type: 'other_skill')
Skill.create!(name: 'NodeJS', skill_type: 'framework')
Skill.create!(name: 'NodeMailer', skill_type: 'library')
Skill.create!(name: 'Notifications', skill_type: 'other_skill')
Skill.create!(name: 'OAuth', skill_type: 'other_skill')
Skill.create!(name: 'OOP', skill_type: 'other_skill')
Skill.create!(name: 'Objective-c', skill_type: 'programming_language')
Skill.create!(name: 'PHP', skill_type: 'programming_language')
Skill.create!(name: 'Passport.js', skill_type: 'framework')
Skill.create!(name: 'Payoneer', skill_type: 'other_skill')
Skill.create!(name: 'Paypal', skill_type: 'other_skill')
Skill.create!(name: 'PhantomJs', skill_type: 'framework')
Skill.create!(name: 'Picasso', skill_type: 'library')
Skill.create!(name: 'Plivo', skill_type: 'other_skill')
Skill.create!(name: 'PostgreSQL', skill_type: 'database')
Skill.create!(name: 'Pusher', skill_type: 'library')
Skill.create!(name: 'Quill.js', skill_type: 'framework')
Skill.create!(name: 'ReactiveX', skill_type: 'other_skill')
Skill.create!(name: 'Redmine', skill_type: 'other_skill')
Skill.create!(name: 'Resque', skill_type: 'library')
Skill.create!(name: 'Rest', skill_type: 'other_skill')
Skill.create!(name: 'Rest API', skill_type: 'other_skill')
Skill.create!(name: 'Retrofit2', skill_type: 'library')
Skill.create!(name: 'Rubocop', skill_type: 'library')
Skill.create!(name: 'Ruby', skill_type: 'programming_language')
Skill.create!(name: 'Ruby on Rails', skill_type: 'framework')
Skill.create!(name: 'RxAndroid', skill_type: 'library')
Skill.create!(name: 'RxJava', skill_type: 'library')
Skill.create!(name: 'S3', skill_type: 'service')
Skill.create!(name: 'SCSS', skill_type: 'programming_language')
Skill.create!(name: 'SNS', skill_type: 'other_skill')
Skill.create!(name: 'SOLID', skill_type: 'other_skill')
Skill.create!(name: 'SQL', skill_type: 'programming_language')
Skill.create!(name: 'SQLite', skill_type: 'library')
Skill.create!(name: 'SSH', skill_type: 'other_skill')
Skill.create!(name: 'SVN', skill_type: 'other_skill')
Skill.create!(name: 'SailsJs', skill_type: 'other_skill')
Skill.create!(name: 'Sass', skill_type: 'programming_language')
Skill.create!(name: 'Sidekiq', skill_type: 'library')
Skill.create!(name: 'Sinatra', skill_type: 'framework')
Skill.create!(name: 'Sketch', skill_type: 'other_skill')
Skill.create!(name: 'Slim', skill_type: 'other_skill')
Skill.create!(name: 'Spark ml', skill_type: 'other_skill')
Skill.create!(name: 'Spring', skill_type: 'framework')
Skill.create!(name: 'Stripe', skill_type: 'other_skill')
Skill.create!(name: 'TDD', skill_type: 'other_skill')
Skill.create!(name: 'Teamcity', skill_type: 'other_skill')
Skill.create!(name: 'Tomcat', skill_type: 'other_skill')
Skill.create!(name: 'Trello', skill_type: 'other_skill')
Skill.create!(name: 'Twilio', skill_type: 'other_skill')
Skill.create!(name: 'Twitter SDK', skill_type: 'framework')
Skill.create!(name: 'Twitter-bootstrap', skill_type: 'library')
Skill.create!(name: 'UI', skill_type: 'other_skill')
Skill.create!(name: 'UX design', skill_type: 'other_skill')
Skill.create!(name: 'Umi-cms', skill_type: 'other_skill')
Skill.create!(name: 'Underscore.js', skill_type: 'library')
Skill.create!(name: 'Vagrant', skill_type: 'other_skill')
Skill.create!(name: 'Vue.js', skill_type: 'framework')
Skill.create!(name: 'Webpacker', skill_type: 'library')
Skill.create!(name: 'Websockets', skill_type: 'other_skill')
Skill.create!(name: 'Woocommerce', skill_type: 'framework')
Skill.create!(name: 'XHTML', skill_type: 'programming_language')
Skill.create!(name: 'Yii', skill_type: 'framework')
Skill.create!(name: 'Zeplin', skill_type: 'other_skill')
Skill.create!(name: 'Zeromq', skill_type: 'other_skill')
Skill.create!(name: 'iOS', skill_type: 'other_skill')
Skill.create!(name: 'lynx', skill_type: 'other_skill')
Skill.create!(name: 'mLab', skill_type: 'other_skill')
Skill.create!(name: 'xCode', skill_type: 'other_skill')