# frozen_string_literal: true

Skill.create!(name: 'API development ')
Skill.create!(name: 'AWS')
Skill.create!(name: 'Active Admin')
Skill.create!(name: 'Ajax')
Skill.create!(name: 'Amazon S3')
Skill.create!(name: 'Amazon EC2')
Skill.create!(name: 'Android')
Skill.create!(name: 'Android SDK')
Skill.create!(name: 'Angular')
Skill.create!(name: 'Angular Material')
Skill.create!(name: 'AngularJs')
Skill.create!(name: 'Ansible')
Skill.create!(name: 'Apache')
Skill.create!(name: 'Apache spark')
Skill.create!(name: 'API-development')
Skill.create!(name: 'Arkit')
Skill.create!(name: 'Autolayout')
Skill.create!(name: 'BDD')
Skill.create!(name: 'Backbone.js')
Skill.create!(name: 'Background jobs')
Skill.create!(name: 'Bigdata')
Skill.create!(name: 'Bitbucket')
Skill.create!(name: 'Bluebird')
Skill.create!(name: 'Bower')
Skill.create!(name: 'C++')
Skill.create!(name: 'CRM')
Skill.create!(name: 'CRUD')
Skill.create!(name: 'Capistrano')
Skill.create!(name: 'Capybara')
Skill.create!(name: 'Carrierwave')
Skill.create!(name: 'Cloudera impala')
Skill.create!(name: 'Cocoa')
Skill.create!(name: 'CocoaPods')
Skill.create!(name: 'Codeship')
Skill.create!(name: 'Coffeescript')
Skill.create!(name: 'Composer')
Skill.create!(name: 'Core Data')
Skill.create!(name: 'Core location')
Skill.create!(name: 'Crashlytics')
Skill.create!(name: 'Cucumber')
Skill.create!(name: 'DRY')
Skill.create!(name: 'Dagger2')
Skill.create!(name: 'Dependency Injection')
Skill.create!(name: 'Devise')
Skill.create!(name: 'Drupal')
Skill.create!(name: 'DynamoDB')
Skill.create!(name: 'E-commerce')
Skill.create!(name: 'Ehcache')
Skill.create!(name: 'Elastic')
Skill.create!(name: 'ElasticSearch')
Skill.create!(name: 'EmberJs')
Skill.create!(name: 'ExpressJS')
Skill.create!(name: 'FabrickJs')
Skill.create!(name: 'Facebook SDK')
Skill.create!(name: 'Flex')
Skill.create!(name: 'GRASP patterns')
Skill.create!(name: 'Git')
Skill.create!(name: 'Glide')
Skill.create!(name: 'Google apis')
Skill.create!(name: 'Google directions')
Skill.create!(name: 'Google maps')
Skill.create!(name: 'Google maps api')
Skill.create!(name: 'Google places')
Skill.create!(name: 'Google SDK')
Skill.create!(name: 'Google services')
Skill.create!(name: 'Google+')
Skill.create!(name: 'Grunt')
Skill.create!(name: 'Gulp')
Skill.create!(name: 'Gulp.js')
Skill.create!(name: 'HDFS')
Skill.create!(name: 'HTML')
Skill.create!(name: 'Hadoop')
Skill.create!(name: 'Hapi.js')
Skill.create!(name: 'Heroku')
Skill.create!(name: 'Hibernate')
Skill.create!(name: 'I18n')
Skill.create!(name: 'J2EE')
Skill.create!(name: 'J2SE')
Skill.create!(name: 'JQuery')
Skill.create!(name: 'JSdom')
Skill.create!(name: 'Jade')
Skill.create!(name: 'Java')
Skill.create!(name: 'Java servlets')
Skill.create!(name: 'Javascript')
Skill.create!(name: 'Jenkins')
Skill.create!(name: 'Jersey')
Skill.create!(name: 'Joomla')
Skill.create!(name: 'JSON')
Skill.create!(name: 'Junit')
Skill.create!(name: 'KnockoutJS')
Skill.create!(name: 'Laravel')
Skill.create!(name: 'LESS')
Skill.create!(name: 'Linux')
Skill.create!(name: 'Lodash.js')
Skill.create!(name: 'MVC')
Skill.create!(name: 'Machine learning')
Skill.create!(name: 'Marketch')
Skill.create!(name: 'Memcached')
Skill.create!(name: 'Mercurial')
Skill.create!(name: 'MongoDB')
Skill.create!(name: 'Mongoose')
Skill.create!(name: 'Morphia')
Skill.create!(name: 'Mustache.js')
Skill.create!(name: 'MySQL')
Skill.create!(name: 'NPM')
Skill.create!(name: 'Native Web Sockets')
Skill.create!(name: 'NodeJS')
Skill.create!(name: 'NodeMailer')
Skill.create!(name: 'Notifications')
Skill.create!(name: 'OAuth')
Skill.create!(name: 'OOP')
Skill.create!(name: 'ORM')
Skill.create!(name: 'Objective-c')
Skill.create!(name: 'Oracle')
Skill.create!(name: 'PHP')
Skill.create!(name: 'Passport.js')
Skill.create!(name: 'Payoneer')
Skill.create!(name: 'Paypal')
Skill.create!(name: 'PhantomJs')
Skill.create!(name: 'Picasso')
Skill.create!(name: 'Plivo')
Skill.create!(name: 'PostgreSQL')
Skill.create!(name: 'Pusher')
Skill.create!(name: 'Quill.js')
Skill.create!(name: 'RESTful')
Skill.create!(name: 'ReactiveX')
Skill.create!(name: 'Redmine')
Skill.create!(name: 'Resque')
Skill.create!(name: 'Rest')
Skill.create!(name: 'Rest API')
Skill.create!(name: 'Retrofit2')
Skill.create!(name: 'Rubocop')
Skill.create!(name: 'Ruby')
Skill.create!(name: 'Ruby on Rails')
Skill.create!(name: 'RxAndroid')
Skill.create!(name: 'RxJava')
Skill.create!(name: 'S3')
Skill.create!(name: 'SCSS')
Skill.create!(name: 'SNS')
Skill.create!(name: 'SOLID')
Skill.create!(name: 'SQL')
Skill.create!(name: 'SQLite')
Skill.create!(name: 'SSH')
Skill.create!(name: 'SVN')
Skill.create!(name: 'SailsJs')
Skill.create!(name: 'Sass')
Skill.create!(name: 'Sidekiq')
Skill.create!(name: 'Sinatra')
Skill.create!(name: 'Sketch')
Skill.create!(name: 'Slim')
Skill.create!(name: 'Spark ml')
Skill.create!(name: 'Spring')
Skill.create!(name: 'Spring MVC')
Skill.create!(name: 'Spring boot')
Skill.create!(name: 'Spring data')
Skill.create!(name: 'Spring framework')
Skill.create!(name: 'Spring security')
Skill.create!(name: 'Stripe')
Skill.create!(name: 'TDD')
Skill.create!(name: 'Teamcity')
Skill.create!(name: 'Tomcat')
Skill.create!(name: 'Trello')
Skill.create!(name: 'Twilio')
Skill.create!(name: 'Twitter SDK')
Skill.create!(name: 'Twitter-bootstrap')
Skill.create!(name: 'UI')
Skill.create!(name: 'UX design')
Skill.create!(name: 'Umi-cms')
Skill.create!(name: 'Underscore.js')
Skill.create!(name: 'Vagrant')
Skill.create!(name: 'Vue.js')
Skill.create!(name: 'Webpack')
Skill.create!(name: 'Webpacker')
Skill.create!(name: 'Websockets')
Skill.create!(name: 'Woocomerce')
Skill.create!(name: 'Woocommerce')
Skill.create!(name: 'XHTML')
Skill.create!(name: 'Yii')
Skill.create!(name: 'Zeplin')
Skill.create!(name: 'Zeromq')
Skill.create!(name: 'iOS')
Skill.create!(name: 'lynx')
Skill.create!(name: 'mLab')
Skill.create!(name: 'xCode')